<?php

namespace DoctrineProxies\__CG__\App\Account\Domain;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Role extends \App\Account\Domain\Role implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'App\\Shared\\Domain\\AggregateRoot'."\0".'events' => ['App\\Shared\\Domain\\AggregateRoot', 'events', null, 16],
        'createdAt' => [parent::class, 'createdAt', parent::class, 16516],
        'events' => ['App\\Shared\\Domain\\AggregateRoot', 'events', null, 16],
        'id' => [parent::class, 'id', parent::class, 16516],
        'name' => [parent::class, 'name', parent::class, 16516],
        'permissions' => [parent::class, 'permissions', parent::class, 16516],
        'slug' => [parent::class, 'slug', parent::class, 16516],
        'updatedAt' => [parent::class, 'updatedAt', parent::class, 16516],
        'users' => [parent::class, 'users', parent::class, 16516],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
